services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - traefik_traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reflex.rule=Host(`rr.orleu.edu.kz`)"
      - "traefik.http.routers.reflex.entrypoints=websecure"
      - "traefik.http.routers.reflex.tls.certresolver=myresolver"
      - "traefik.http.services.reflex.loadbalancer.server.port=8000"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  traefik_traefik-net:
    external: true
